name: "Test"
description: "Playground"

runs:
  using: "composite"
  steps:
    - run: ls -al ${{ github.action_path }}
      shell: bash
    - run: ls -al ${{ github.action_path }}/submodule
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: PopTracker/pack-checker
        path: ${{ github.action_path }}/pack-checker
        submodules: true
    - run: ls -al ${{ github.action_path }}/pack-checker
      shell: bash
    - run: |
        pip install -r "${{ github.action_path }}/pack-checker/requirements.txt"
        python "${{ github.action_path }}/pack-checker/pack_checker.py" --help
      shell: bash

