name: "Test"
description: "Playground"

runs:
  using: "composite"
  steps:
    - name: "Checkout pack-checker"
      uses: actions/checkout@v3
      with:
        repository: PopTracker/pack-checker
        path: .pack-checker
        submodules: true
    - name: "Move pack-checker"
      run: mv .pack-checker "${{ github.action_path }}/pack-checker"
      shell: bash
    - run: ls -al ${{ github.action_path }}/pack-checker
      shell: bash
    - run: |
        pip install -r "${{ github.action_path }}/pack-checker/requirements.txt"
        python "${{ github.action_path }}/pack-checker/pack_checker.py" --help
      shell: bash

