name: "Test"
description: "Playground"

inputs:
  strict:
    description: 'true for strict mode, false for lax mode'
    type: string
    required: true
    default: false

runs:
  using: "composite"
  steps:
    - name: "Checking out pack-checker"
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        [ -d pack-checker ] || git clone -q --branch v1 --depth 1 --recurse-submodules https://github.com/PopTracker/pack-checker.git
    - name: "Running pack-checker (lax)"
      if: ${{ inputs.strict == 'false' }}
      shell: bash
      run: |
        echo "lax"
        pip install -r "${{ github.action_path }}/pack-checker/requirements.txt"
        python "${{ github.action_path }}/pack-checker/pack_checker.py" -b --help
    - name: "Running pack-checker (strict)"
      if: ${{ inputs.strict != 'false' }}
      shell: bash
      run: |
        echo "strict"
        pip install -r "${{ github.action_path }}/pack-checker/requirements.txt"
        python "${{ github.action_path }}/pack-checker/pack_checker.py" -b --strict --help
    - run: ls -al; echo "$PWD"
      shell: bash

