name: "Test"
description: "Playground"

runs:
  using: "composite"
  steps:
    - name: "Checking out pack-checker"
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        git clone --branch v1 --depth 1 --recurse-submodules https://github.com/PopTracker/pack-checker.git
    - name: "Running pack-checker"
      shell: bash
      run: |
        pip install -r "${{ github.action_path }}/pack-checker/requirements.txt"
        python "${{ github.action_path }}/pack-checker/pack_checker.py" --help
    - run: ls -al; echo "$PWD"
      shell: bash

